# Generated by Django 4.1.3 on 2022-11-25 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("file_service", "0002_directory_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="root_directory",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="root_for",
                to="file_service.directory",
            ),
        ),
        migrations.AlterField(
            model_name="directory",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="directory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
