# Generated by Django 4.1.3 on 2022-11-25 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("file_service", "0003_user_root_directory_alter_directory_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="root_directory",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="root_for",
                to="file_service.directory",
            ),
        ),
    ]
