# Generated by Django 4.1.3 on 2023-01-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_service", "0004_directory_private_file_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="oauth_provider",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.TextField(null=True, unique=True),
        ),
    ]
