# Generated by Django 4.1.3 on 2022-11-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("file_service", "0004_alter_user_root_directory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="root_directory",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="root_for",
                to="file_service.directory",
            ),
        ),
    ]
