# Generated by Django 4.1.3 on 2023-01-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_service", "0006_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.TextField(null=True),
        ),
    ]
