version: "2.4"

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    command: postgres -c 'max_connections=100'
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./logs/dev/db:/var/log/postgresql
    environment:
      - POSTGRES_DB=fileplace
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=haslo123

  backend:
    build: ./backend
    restart: unless-stopped
    volumes:
      - ./backend:/code
    ports:
      - "80:80"
    depends_on:
      - db
    init: true
